# .prettierrc or .prettierrc.yaml
# prettier.config.js or .prettierrc.js
# resource: https://prettier.io/docs/en/configuration.html
trailingComma: 'all'
tabWidth: 2
semi: true
singleQuote: true
overrides:
  - files: 
    - '*.js'
    - '*.jsx'
    options:
      bracketSpacing: true
      jsxSingleQuote: true
      semi: true
      singleQuote: true
      tabWidth: 2
      useTabs: false
  - files:
    - '*.ts'
    options:
      tabWidth: 2
